name: "Validate JSON"
on:
  pull_request:
    paths:
      - "**.json"

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed JSON files
        id: changed
        uses: tj-actions/changed-files@v45
        with:
          files: "**.json"
          separator: "\n"

      - name: Validate JSON files
        if: steps.changed.outputs.any_changed == 'true'
        uses: GrantBirki/json-yaml-validate@v3
        with:
          comment: "true"
          use_gitignore: "true"
          files: ${{ steps.changed.outputs.all_changed_files }}
